# Generated by Django 5.1.4 on 2025-01-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_visuleouser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='visuleouser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Boolean field to mark if this user is staff.', verbose_name='is staff'),
        ),
    ]
