# Generated by Django 5.1.4 on 2025-01-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_visuleouser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertag',
            name='slug',
            field=models.SlugField(blank=True, help_text='Slug of the user type.', max_length=255, null=True, unique=True, verbose_name='slug'),
        ),
    ]
