# Generated by Django 5.0.1 on 2024-11-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visuleouser',
            name='username',
            field=models.CharField(blank=True, help_text="User's username.", max_length=255, null=True, verbose_name='username'),
        ),
    ]
