# Generated by Django 5.0.1 on 2024-01-24 18:24

import django.db.models.deletion
import utils.main
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.UUIDField(default=utils.main.generate_uuid, editable=False, help_text='Unique identifier for this object.', primary_key=True, serialize=False, verbose_name='id')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time when this object was created.', verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date and time when this object was last modified.', verbose_name='modified')),
                ('is_deleted', models.BooleanField(default=False, help_text='Boolean field to mark if this object is deleted.', verbose_name='is deleted')),
                ('name', models.CharField(help_text='Name of the category.', max_length=255, verbose_name='name')),
                ('description', models.TextField(help_text='Description of the category.', verbose_name='description')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.UUIDField(default=utils.main.generate_uuid, editable=False, help_text='Unique identifier for this object.', primary_key=True, serialize=False, verbose_name='id')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time when this object was created.', verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date and time when this object was last modified.', verbose_name='modified')),
                ('is_deleted', models.BooleanField(default=False, help_text='Boolean field to mark if this object is deleted.', verbose_name='is deleted')),
                ('name', models.CharField(help_text='Name of the skill.', max_length=255, verbose_name='name')),
                ('description', models.TextField(help_text='Description of the skill.', verbose_name='description')),
                ('is_featured', models.BooleanField(default=False, help_text='Boolean field to mark if this skill is featured.', verbose_name='is featured')),
            ],
            options={
                'verbose_name': 'skill',
                'verbose_name_plural': 'skills',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.UUIDField(default=utils.main.generate_uuid, editable=False, help_text='Unique identifier for this object.', primary_key=True, serialize=False, verbose_name='id')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time when this object was created.', verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date and time when this object was last modified.', verbose_name='modified')),
                ('is_deleted', models.BooleanField(default=False, help_text='Boolean field to mark if this object is deleted.', verbose_name='is deleted')),
                ('name', models.CharField(help_text='Name of the project.', max_length=255, verbose_name='name')),
                ('slug', models.SlugField(help_text='Slug for the project.', max_length=255, unique=True, verbose_name='slug')),
                ('description', models.TextField(help_text='Description of the project.', verbose_name='description')),
                ('display_image', models.ImageField(help_text='Image for the project.', upload_to='projects/', verbose_name='image')),
                ('url', models.URLField(help_text='URL for the project.', max_length=255, verbose_name='url')),
                ('is_featured', models.BooleanField(default=False, help_text='Boolean field to mark if this project is featured.', verbose_name='is featured')),
                ('categories', models.ManyToManyField(help_text='Categories for the project.', related_name='projects', to='portfolio.categories', verbose_name='categories')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectImages',
            fields=[
                ('id', models.UUIDField(default=utils.main.generate_uuid, editable=False, help_text='Unique identifier for this object.', primary_key=True, serialize=False, verbose_name='id')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time when this object was created.', verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date and time when this object was last modified.', verbose_name='modified')),
                ('is_deleted', models.BooleanField(default=False, help_text='Boolean field to mark if this object is deleted.', verbose_name='is deleted')),
                ('image', models.ImageField(help_text='Image for the project.', upload_to='projects/', verbose_name='image')),
                ('project_image_id', models.IntegerField(help_text='Project image id.', verbose_name='project image id')),
                ('project', models.ForeignKey(help_text='Project for the image.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.projects', verbose_name='project')),
            ],
            options={
                'verbose_name': 'project image',
                'verbose_name_plural': 'project images',
            },
        ),
    ]
