name: scp files
on:
  push:
    branches:
      - main
jobs:

  deploy_project:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          since_last_remote_commit: true
          separator: ","

      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: "104.43.210.41"
          username: "yokwejuste"
          password: "Password123!"
          port: "22"
          source: "."
          target: ${{ github.event.repository.name }}

  build_project:
    name: Build
    needs: deploy_project
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: "104.43.210.41"
          username: "yokwejuste"
          password: "Password123!"
          port: "22"
          script: |
            cd visuleo_port
            docker compose up -d --build